// Code generated by simplemock. DO NOT EDIT.
package resolves_args_test

import "os"

type ResolvesArgMock struct {
	ResolvesArgFunc func(file *os.File)
}

func (m *ResolvesArgMock) ResolvesArg(file *os.File) {
	if m.ResolvesArgFunc != nil {
		return m.ResolvesArgFunc(file)
	}
	panic("ResolvesArg called with nil ResolvesArgFunc!")
}
