// Code generated by simplemock. DO NOT EDIT.
package imported_args_test

import "os"

type ImportedArgMock struct {
	ImportedArgFunc func(*os.File)
}

func (m *ImportedArgMock) ImportedArg(arg0 *os.File) {
	if m.ImportedArgFunc != nil {
		return m.ImportedArgFunc(arg0)
	}
	panic("ImportedArg called with nil ImportedArgFunc!")
}
