package main

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path"
	"sort"
	"strings"

	"github.com/mcriley821/simplemock/env"

	"golang.org/x/mod/modfile"
)

var (
	genLine = []byte("// Code generated by simplemock. DO NOT EDIT.\n")
)

func GenerateMockFromAst(symbol string, writer io.Writer, env *env.GoEnv) error {
	pkg, name, found := strings.Cut(symbol, ".")
	if !found {
		pkg, name = name, pkg
	}

	fset := token.NewFileSet()
	astFile, err := parser.ParseFile(fset, env.GOFILE, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("parsing file: %w", err)
	}

	ifaceType, err := findInterface(pkg, name, env, astFile)
	if err != nil {
		return fmt.Errorf("resolving interface '%s': %w", symbol, err)
	}

	mockStruct, types, err := ifaceToMockStruct(ifaceType)
	if err != nil {
		return fmt.Errorf("generating mock struct: %w", err)
	}

	imports := resolveTypes(types, astFile)

	mockMethods := mockMethods(name, ifaceType)
	decls := make([]ast.Decl, 0)
	if imports != nil {
		sortImports(imports)
		decls = append(decls, imports)
	}
	decls = append(decls, &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: &ast.Ident{Name: name + "Mock"},
				Type: mockStruct,
			},
		},
	})
	decls = append(decls, mockMethods...)

	if _, err := writer.Write(genLine); err != nil {
		return fmt.Errorf("writing generated comment: %w", err)
	}

	pkgName := astFile.Name.Name
	if !strings.HasSuffix(pkgName, "_test") {
		pkgName += "_test"
	}

	err = format.Node(writer, fset, &ast.File{
		Name:      &ast.Ident{Name: pkgName},
		Imports:   astFile.Imports,
		Decls:     decls,
		GoVersion: astFile.GoVersion,
	})
	if err != nil {
		return fmt.Errorf("writing generated ast: %w", err)
	}
	return nil
}

func findInterface(pkg, name string, env *env.GoEnv, fileAST *ast.File) (*ast.InterfaceType, error) {
	if pkg == "" {
		for _, decl := range fileAST.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if typeSpec.Name.Name != name {
					continue
				}

				if iType, ok := typeSpec.Type.(*ast.InterfaceType); !ok {
					return nil, fmt.Errorf("type '%s' is not an interface", name)
				} else {
					return iType, nil
				}
			}
		}
	} else {
		var importSource string

		for _, importSpec := range fileAST.Imports {
			impPath := strings.Trim(importSpec.Path.Value, "\"")

			var mod *modfile.File
			var std, gomod string
			var err error

			if importSpec.Name != nil && importSpec.Name.Name == pkg {
				importSource = impPath
				goto resolveSymbol
			}

			// check stdlib
			std = path.Join(env.GOROOT, "src", impPath)
			if _, err := os.Stat(std); err == nil {
				importSource = std
				goto resolveSymbol
			}

			// check go.mod
			gomod, err = findModuleRoot(env.GOFILE)
			if err == nil {
				data, err := os.ReadFile(gomod)
				if err != nil {
					return nil, fmt.Errorf("reading go.mod: %w", err)
				}
				mod, err = modfile.Parse(gomod, data, nil)
				if err != nil {
					return nil, fmt.Errorf("parsing go.mod: %w", err)
				}
				if strings.HasPrefix(impPath, mod.Module.Mod.Path) {
					importSource = strings.Replace(impPath, mod.Module.Mod.Path, path.Dir(gomod), 1)
					goto resolveSymbol
				}
			}

			// check gomodcache
			for _, require := range mod.Require {
				if strings.HasPrefix(impPath, require.Mod.Path) {
					submod := strings.TrimPrefix(impPath, require.Mod.Path)
					modPath := path.Join(env.GOMODCACHE, require.Mod.String(), submod)
					println("checking ", modPath)
					if _, err := os.Stat(modPath); err == nil {
						importSource = modPath
						goto resolveSymbol
					}
				}
			}

			continue

		resolveSymbol:
			entries, err := os.ReadDir(importSource)
			if err != nil {
				return nil, fmt.Errorf("reading package '%s': %w", importSource, err)
			}
			for _, entry := range entries {
				if entry.IsDir() {
					continue
				}

				if base, found := strings.CutSuffix(entry.Name(), ".go"); !found {
					continue
				} else if strings.HasSuffix(base, "_test") {
					continue
				}

				fullPath := path.Join(importSource, entry.Name())
				AST, err := parser.ParseFile(&token.FileSet{}, fullPath, nil, parser.SkipObjectResolution)
				if err != nil {
					continue
				}

				iType, err := findInterface("", name, env, AST)
				if err != nil {
					continue
				}

				return iType, nil
			}
		}
	}
	return nil, fmt.Errorf("could not find interface '%s'", name)
}

func ifaceToMockStruct(ifaceType *ast.InterfaceType) (*ast.StructType, []ast.Expr, error) {
	members := methodsToMockMembers(ifaceType.Methods.List)

	types := make([]ast.Expr, 0)
	for _, member := range members {
		fType := member.Type.(*ast.FuncType)
		for _, param := range fType.Params.List {
			types = append(types, param.Type)
		}
		if fType.Results != nil {
			for _, result := range fType.Results.List {
				types = append(types, result.Type)
			}
		}
	}

	structType := &ast.StructType{
		Fields: &ast.FieldList{
			List: members,
		},
	}

	return structType, types, nil
}

func methodsToMockMembers(methods []*ast.Field) []*ast.Field {
	ret := make([]*ast.Field, 0, len(methods))

	for _, method := range methods {
		names := make([]*ast.Ident, 0, len(method.Names))
		for _, name := range method.Names {
			names = append(names, &ast.Ident{Name: name.Name + "Func"})
		}
		ret = append(ret, &ast.Field{
			Names: names,
			Type:  method.Type,
		})
	}

	return ret
}

func mockMethods(name string, ifaceType *ast.InterfaceType) []ast.Decl {
	decls := make([]ast.Decl, 0)

	for _, method := range ifaceType.Methods.List {
		decls = append(decls, &ast.FuncDecl{
			Name: &ast.Ident{Name: method.Names[0].Name},
			Recv: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							{Name: "m"},
						},
						Type: &ast.StarExpr{
							X: &ast.Ident{
								Name: name + "Mock",
							},
						},
					},
				},
			},
			Type: &ast.FuncType{
				Params:  defaultedArgs(method.Type.(*ast.FuncType).Params.List),
				Results: method.Type.(*ast.FuncType).Results,
			},
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					&ast.IfStmt{
						Cond: &ast.BinaryExpr{
							X: &ast.SelectorExpr{
								X:   &ast.Ident{Name: "m"},
								Sel: &ast.Ident{Name: method.Names[0].Name + "Func"},
							},
							Op: token.NEQ,
							Y:  &ast.Ident{Name: "nil"},
						},
						Body: &ast.BlockStmt{
							List: []ast.Stmt{
								&ast.ReturnStmt{
									Results: []ast.Expr{
										&ast.CallExpr{
											Fun: &ast.SelectorExpr{
												X:   &ast.Ident{Name: "m"},
												Sel: &ast.Ident{Name: method.Names[0].Name + "Func"},
											},
											Args: fieldsToExprs(defaultedArgs(method.Type.(*ast.FuncType).Params.List)),
										},
									},
								},
							},
						},
					},
					&ast.ExprStmt{
						X: &ast.CallExpr{
							Fun: &ast.Ident{
								Name: "panic",
							},
							Args: []ast.Expr{
								&ast.BasicLit{
									Kind:  token.STRING,
									Value: fmt.Sprintf("\"%s called with nil %[1]sFunc!\"", method.Names[0].Name),
								},
							},
						},
					},
				},
			},
		})
	}

	return decls
}

func resolveTypes(types []ast.Expr, astFile *ast.File) ast.Decl {
	specs := make([]ast.Spec, 0)

	for _, aType := range types {
		pkg := typeIdent(aType)
		if pkg == nil {
			continue
		}

		var importSpec *ast.ImportSpec = nil
		for _, imp := range astFile.Imports {
			if strings.Trim(path.Base(imp.Path.Value), "\"") == pkg.Name {
				importSpec = imp
				break
			}
		}

		if importSpec != nil {
			specs = append(specs, importSpec)
		}
	}

	if len(specs) == 0 {
		return nil
	}

	return &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: specs,
	}
}

func typeIdent(expr ast.Expr) *ast.Ident {
	switch iType := expr.(type) {
	case *ast.StarExpr:
		return typeIdent(iType.X)
	case *ast.SelectorExpr:
		return iType.X.(*ast.Ident)
	}
	return nil
}

func fieldsToExprs(fields *ast.FieldList) []ast.Expr {
	exprs := make([]ast.Expr, 0, len(fields.List))
	for _, field := range fields.List {
		for _, name := range field.Names {
			exprs = append(exprs, &ast.Ident{Name: name.Name})
		}
	}
	return exprs
}

func defaultedArgs(fields []*ast.Field) *ast.FieldList {
	ret := make([]*ast.Field, 0, len(fields))
	for i, field := range fields {
		names := make([]*ast.Ident, 0, len(field.Names))
		for _, name := range field.Names {
			names = append(names, &ast.Ident{Name: name.Name})
		}
		if len(names) == 0 {
			names = append(names, &ast.Ident{Name: fmt.Sprintf("arg%d", i)})
		}
		ret = append(ret, &ast.Field{
			Names: names,
			Type:  field.Type,
		})
	}
	return &ast.FieldList{List: ret}
}

func sortImports(imports ast.Decl) {
	specs := imports.(*ast.GenDecl).Specs
	sort.Slice(specs, func(i, j int) bool {
		return specs[i].(*ast.ImportSpec).Path.Value < specs[j].(*ast.ImportSpec).Path.Value
	})
}

func findModuleRoot(source string) (string, error) {
	dir := path.Dir(source)

	for dir != string(os.PathSeparator) {
		gomod := path.Join(dir, "go.mod")
		if fd, err := os.Stat(gomod); err == nil && !fd.IsDir() {
			return gomod, nil
		}
		dir = path.Dir(dir)
	}
	return "", errors.New("cannot find go.mod")
}
