package main

import (
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"path/filepath"
	"runtime/debug"
	"slices"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const (
	usageLine = `
Usage: simplemock [-help] [-version] [-mock-name name] -iface interface -out outfile

Options:
`

	longHelp = `
simplemock generates mock implementations for interfaces and is designed to be
used with //go:generate directives to streamline usage and cohesiveness. Mocks
can be generated for any interface defined within the scope of the source file,
including interfaces that have been imported.

The required option -iface specifies the identifier of the interface for which
a mock is to be generated. This should match the interface name as it would
appear in the source file if it were to be used directly. For package-scoped
interfaces, this would simply be the interface name, e.g. 'MyInterface'. For
interfaces that have been imported, this would be its qualified identifier,
e.g. 'io.Reader'.

The required option -out specifies a relative file path where the generated
mock will be written. This path is relative to the source file. The special
value "os.Stdout" indicates that the generated mock should be printed to stdout
instead of written to disk.

Generated mocks will be defined in the test package corresponding to the
package of the source file. In the case the source file is within the main
package, the mock will also be defined in the main package.

The optional flag -mock-name specifies the name of the generated mock struct.
If not provided, the mock will be named {Interface}Mock by default.

Mock structs export members corresponding to each method of the interface,
named with a "Func" suffix. When the mocked method is invoked, the call is
forwarded to the corresponding member. If the member is not implemented, and
thus nil, the mocked method will panic.
`
)

type typeParam struct {
	Name       string
	Constraint string
}

type templData struct {
	PackageName   string
	Imports       []*packages.Package
	InterfaceName string
	MockName      string
	Methods       []*types.Func
	TypeParams    []typeParam
}

var (
	templ = template.Must(template.New("MockSource").Funcs(template.FuncMap{
		"typeString":    typeString,
		"signature":     signature,
		"args":          defaultedArgs,
		"typeParamDecl": typeParamDecl,
		"typeParamUse":  typeParamUse,
		"isVoid":        func(sig *types.Signature) bool { return sig.Results().Len() == 0 },
	}).Parse(
		`// Code generated by simplemock. DO NOT EDIT.
package {{ .PackageName }}
{{- with .Imports }}

import (
{{- range . }}
	"{{ .PkgPath }}"
{{- end }}
)

{{- end }}
{{- if .TypeParams }}

func _{{ typeParamDecl .TypeParams }}() { var _ {{ .InterfaceName }}{{ typeParamUse .TypeParams }} = &{{ .MockName }}{{ typeParamUse .TypeParams }}{} }
{{- else }}

var _ {{ .InterfaceName }} = &{{ .MockName }}{}
{{- end }}

{{- $mockName := .MockName }}
{{- $tpDecl := typeParamDecl .TypeParams }}
{{- $tpUse := typeParamUse .TypeParams }}
{{ with .Methods }}
type {{ $mockName }}{{ $tpDecl }} struct {
{{- range . }}
	{{ .Name }}Func {{ typeString .Type }}
{{- end }}
}
{{- else }}
type {{ $mockName }}{{ $tpDecl }} struct {}
{{- end }}
{{- range .Methods }}

func (m *{{ $mockName }}{{ $tpUse }}) {{ .Name }}{{ signature .Signature }} {
	if m.{{ .Name }}Func != nil {
		{{- if isVoid .Signature }}
		m.{{ .Name }}Func({{ args .Signature }})
		return
		{{- else }}
		return m.{{ .Name }}Func({{ args .Signature }})
		{{- end }}
	}
	panic("{{ .Name }} called with nil {{ .Name }}Func!")
}
{{- end }}
`,
	))
)

func usage() {
	f := flag.CommandLine.Output()

	fmt.Fprint(f, usageLine[1:]) // trim newline
	flag.PrintDefaults()
}

func helpExit(string) error {
	flag.CommandLine.SetOutput(os.Stdout)
	usage()
	fmt.Fprint(os.Stdout, longHelp)
	os.Exit(0)
	return nil
}

func versionExit(string) error {
	if info, ok := debug.ReadBuildInfo(); ok {
		fmt.Printf("version: %s\n", info.Main.Version)
		os.Exit(0)
	}
	fmt.Fprintln(os.Stderr, "Failed reading build info?")
	os.Exit(1)
	return nil
}

func main() {
	if err := exec(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "An error occurred:", err)
		os.Exit(1)
	}
	os.Exit(0)
}

func exec() error {
	flag.Usage = usage

	var typeName, fname, mockName string

	flag.StringVar(&typeName, "iface", "", "interface to generate a mock for")
	flag.StringVar(&fname, "out", "", "relative output file")
	flag.StringVar(&mockName, "mock-name", "", "name for the generated mock struct (default: {Interface}Mock)")
	flag.BoolFunc("version", "print version and exit", versionExit)
	flag.BoolFunc("help", "print detailed help and exit", helpExit)
	flag.Parse()

	if typeName == "" {
		return errors.New("option '-iface' is required")
	}

	if fname == "" {
		return errors.New("option '-out' is required")
	}

	inputFile := os.Getenv("GOFILE")
	if inputFile == "" {
		return errors.New("environment variable GOFILE is required")
	}

	cfg := packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedImports |
			packages.NeedDeps |
			packages.NeedTypes |
			packages.NeedSyntax |
			packages.NeedTypesInfo,
		Tests: true,
	}

	pkgs, err := packages.Load(&cfg, "file="+inputFile)
	if err != nil {
		return fmt.Errorf("loading input package: %w", err)
	}

	if len(pkgs) == 0 {
		return fmt.Errorf("finding packages for file: %s", inputFile)
	}

	for _, pkg := range pkgs {
		for _, e := range pkg.Errors {
			if e.Kind == packages.ListError || e.Kind == packages.ParseError {
				return fmt.Errorf("loading package %s: %w", pkg.Name, e)
			}
		}
	}

	absInput, absErr := filepath.Abs(inputFile)
	if absErr != nil {
		absInput = inputFile
	}

	sourcePkg := findSourcePkg(pkgs, absInput)
	if sourcePkg == nil {
		return fmt.Errorf("finding package containing %s", inputFile)
	}

	obj := sourcePkg.Types.Scope().Lookup(typeName)
	if obj == nil {
		if pkgName, ifaceName, found := strings.Cut(typeName, "."); found {
			importPaths := make([]string, 0, len(sourcePkg.Imports))
			for path := range sourcePkg.Imports {
				importPaths = append(importPaths, path)
			}
			sort.Strings(importPaths)
			for _, importPath := range importPaths {
				pkg := sourcePkg.Imports[importPath]
				if pkg.Name != pkgName {
					continue
				}
				obj = pkg.Types.Scope().Lookup(ifaceName)
				if obj != nil {
					pkgs = append(pkgs, pkg)
					break
				}
			}
		}
		if obj == nil {
			return fmt.Errorf("finding type: %s", typeName)
		}
	}

	if _, ok := obj.(*types.TypeName); !ok {
		return fmt.Errorf("expected a named type: %v", obj)
	}

	if !types.IsInterface(obj.Type()) {
		return fmt.Errorf("expected an interface: %v", obj)
	}

	if !obj.Exported() {
		return fmt.Errorf("must be exported: %v", obj)
	}

	imports, err := importsUsedBy(obj, pkgs)
	if err != nil {
		return fmt.Errorf("getting %v imports: %w", obj, err)
	}

	iface := obj.Type().Underlying().(*types.Interface)
	methods := make([]*types.Func, iface.NumMethods())
	for i := range methods {
		methods[i] = iface.Method(i)
	}

	var typeParams []typeParam
	if named, ok := obj.Type().(*types.Named); ok {
		if tps := named.TypeParams(); tps != nil {
			for i := range tps.Len() {
				tp := tps.At(i)
				typeParams = append(typeParams, typeParam{
					Name:       tp.Obj().Name(),
					Constraint: constraintString(tp.Constraint()),
				})
			}
		}
	}

	pkgName := sourcePkg.Name
	if pkgName != "main" {
		pkgName = strings.TrimSuffix(sourcePkg.Name, "_test") + "_test"
	}

	file := os.Stdout
	if fname != "os.Stdout" {
		file, err = os.Create(filepath.Join(filepath.Dir(inputFile), fname))
		if err != nil {
			return fmt.Errorf("creating output file '%s': %w", fname, err)
		}
		defer file.Close()
	}

	if mockName == "" {
		mockName = obj.Name() + "Mock"
	}

	// types.TypeString for a generic named type includes the type parameter
	// constraints (e.g. "Repo[T any]"), which is only valid in a declaration
	// context.  For the instantiation site in the compile-time check we need
	// just the base name; type arguments are appended separately by the template.
	ifaceName := types.TypeString(obj.Type(), relativeTo)
	if len(typeParams) > 0 {
		if idx := strings.Index(ifaceName, "["); idx != -1 {
			ifaceName = ifaceName[:idx]
		}
	}

	if err = templ.Execute(file, templData{
		PackageName:   pkgName,
		Imports:       imports,
		InterfaceName: ifaceName,
		MockName:      mockName,
		Methods:       methods,
		TypeParams:    typeParams,
	}); err != nil {
		return fmt.Errorf("generating mock from template: %w", err)
	}

	return nil
}

func importsUsedBy(obj types.Object, pkgs []*packages.Package) ([]*packages.Package, error) {
	var pkg *packages.Package = nil
	for _, p := range pkgs {
		if p.Types == obj.Pkg() {
			pkg = p
		}
	}
	if pkg == nil {
		return nil, errors.New("owning package not found")
	}

	var id *ast.Ident = nil
	for ident, object := range pkg.TypesInfo.Defs {
		if object == obj {
			id = ident
			break
		}
	}
	if id == nil {
		return nil, errors.New("ast mapping not found")
	}

	typeSpec, ok := id.Obj.Decl.(*ast.TypeSpec)
	if !ok {
		return nil, errors.New("ast decl is not a type")
	}

	v := interfaceVisitor{info: pkg.TypesInfo, pkgs: make(map[*types.Package]struct{})}
	ast.Walk(&v, typeSpec)

	imports := make([]*packages.Package, 0, len(v.pkgs)+1)

	if pkg.Name != "main" {
		imports = append(imports, pkg)
	}

	for tPkg := range v.pkgs {
		for _, pPkg := range pkg.Imports {
			if tPkg == pPkg.Types {
				imports = append(imports, pPkg)
			}
		}
	}
	sort.Slice(imports, func(i, j int) bool {
		return imports[i].PkgPath < imports[j].PkgPath
	})
	return imports, nil
}

type interfaceVisitor struct {
	info *types.Info
	pkgs map[*types.Package]struct{}
}

func (v *interfaceVisitor) Visit(node ast.Node) ast.Visitor {
	if id, ok := node.(*ast.Ident); ok {
		obj := v.info.Uses[id]
		if obj == nil {
			obj = v.info.Defs[id]
		}

		if obj != nil && obj.Pkg() != nil {
			v.pkgs[obj.Pkg()] = struct{}{}
		}
	}
	return v
}

func typeString(typ types.Type) string {
	return types.TypeString(typ, (*types.Package).Name)
}

func signature(sig *types.Signature) string {
	params := sig.Params()
	args := make([]string, params.Len())
	for i := range args {
		param := params.At(i)
		if name := params.At(i).Name(); name == "" {
			args[i] = fmt.Sprintf("arg%d", i)
		} else {
			args[i] = name
		}

		if i == params.Len()-1 && sig.Variadic() {
			args[i] += " ..." + strings.TrimPrefix(typeString(param.Type()), "[]")
		} else {
			args[i] += " " + typeString(param.Type())
		}
	}

	argsStr := strings.Join(args, ", ")
	switch sig.Results().Len() {
	case 0:
		return fmt.Sprintf("(%s)", argsStr)
	case 1:
		return fmt.Sprintf("(%s) %s", argsStr, typeString(sig.Results().At(0).Type()))
	default:
		return fmt.Sprintf("(%s) %s", argsStr, typeString(sig.Results()))
	}
}

func defaultedArgs(sig *types.Signature) string {
	params := sig.Params()
	args := make([]string, params.Len())
	for i := range args {
		if name := params.At(i).Name(); name == "" {
			args[i] = fmt.Sprintf("arg%d", i)
		} else {
			args[i] = name
		}
	}

	ret := strings.Join(args, ", ")
	if sig.Variadic() {
		return ret + "..."
	}
	return ret
}

func findSourcePkg(pkgs []*packages.Package, absInput string) *packages.Package {
	for _, pkg := range pkgs {
		if slices.Contains(pkg.GoFiles, absInput) {
			return pkg
		}
	}
	return nil
}

func relativeTo(pkg *types.Package) string {
	if pkg.Name() == "main" {
		return types.RelativeTo(pkg)(pkg)
	}
	return (*types.Package).Name(pkg)
}

// constraintString returns the source-level string for a type parameter
// constraint, using "any" for the empty interface.
func constraintString(c types.Type) string {
	if iface, ok := c.(*types.Interface); ok && iface.NumMethods() == 0 && iface.NumEmbeddeds() == 0 {
		return "any"
	}
	return types.TypeString(c, (*types.Package).Name)
}

// typeParamDecl renders a type parameter list for a declaration, e.g. "[T any, K comparable]".
// Returns an empty string when params is nil or empty.
func typeParamDecl(params []typeParam) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = p.Name + " " + p.Constraint
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// typeParamUse renders a type argument list for use at an instantiation site,
// e.g. "[T, K]". Returns an empty string when params is nil or empty.
func typeParamUse(params []typeParam) string {
	if len(params) == 0 {
		return ""
	}
	names := make([]string, len(params))
	for i, p := range params {
		names[i] = p.Name
	}
	return "[" + strings.Join(names, ", ") + "]"
}
