// Code generated by simplemock. DO NOT EDIT.
package input_test

import (
	"testing"
	"github.com/stretchr/testify/suite"
)

type TestingSuiteMock struct {
	TFunc    func() *testing.T
	SetTFunc func(*testing.T)
	SetSFunc func(suite suite.TestingSuite)
}

func (m *TestingSuiteMock) T() *testing.T {
	if m.TFunc != nil {
		return m.TFunc()
	}
	panic("T called with nil TFunc!")
}
func (m *TestingSuiteMock) SetT(arg0 *testing.T) {
	if m.SetTFunc != nil {
		return m.SetTFunc(arg0)
	}
	panic("SetT called with nil SetTFunc!")
}
func (m *TestingSuiteMock) SetS(suite suite.TestingSuite) {
	if m.SetSFunc != nil {
		return m.SetSFunc(suite)
	}
	panic("SetS called with nil SetSFunc!")
}
