// Code generated by simplemock. DO NOT EDIT.
package input_test

type AfterTestMock struct {
	AfterTestFunc func(suiteName, testName string)
}

func (m *AfterTestMock) AfterTest(suiteName, testName string) {
	if m.AfterTestFunc != nil {
		return m.AfterTestFunc(suiteName, testName)
	}
	panic("AfterTest called with nil AfterTestFunc!")
}
