// Code generated by simplemock. DO NOT EDIT.
package void_func_test

type VoidMock struct {
	VoidFunc func()
}

func (m *VoidMock) Void() {
	if m.VoidFunc != nil {
		return m.VoidFunc()
	}
	panic("Void called with nil VoidFunc!")
}
