// Code generated by simplemock. DO NOT EDIT.
package multi_return_test

type MultiReturnMock struct {
	MultiReturnFunc func() (int, error)
}

func (m *MultiReturnMock) MultiReturn() (int, error) {
	if m.MultiReturnFunc != nil {
		return m.MultiReturnFunc()
	}
	panic("MultiReturn called with nil MultiReturnFunc!")
}
