// Code generated by simplemock. DO NOT EDIT.
package named_args_test

type NamedArgsMock struct {
	NamedArgsFunc func(x, y int)
}

func (m *NamedArgsMock) NamedArgs(x, y int) {
	if m.NamedArgsFunc != nil {
		return m.NamedArgsFunc(x, y)
	}
	panic("NamedArgs called with nil NamedArgsFunc!")
}
