// Code generated by simplemock. DO NOT EDIT.
package single_arg_test

type SingleArgMock struct {
	SingleArgFunc func(int)
}

func (m *SingleArgMock) SingleArg(arg0 int) {
	if m.SingleArgFunc != nil {
		return m.SingleArgFunc(arg0)
	}
	panic("SingleArg called with nil SingleArgFunc!")
}
