// Code generated by simplemock. DO NOT EDIT.
package just_args_test

type JustArgsMock struct {
	JustArgsFunc func(int, int)
}

func (m *JustArgsMock) JustArgs(arg0 int, arg1 int) {
	if m.JustArgsFunc != nil {
		return m.JustArgsFunc(arg0, arg1)
	}
	panic("JustArgs called with nil JustArgsFunc!")
}
