// Code generated by simplemock. DO NOT EDIT.
package resolves_multi_args_test

import (
	"net/url"
	"os"
)

type ResolvesMultiArgsMock struct {
	ResolvesMultiArgsFunc func(*os.File, *url.URL)
}

func (m *ResolvesMultiArgsMock) ResolvesMultiArgs(arg0 *os.File, arg1 *url.URL) {
	if m.ResolvesMultiArgsFunc != nil {
		return m.ResolvesMultiArgsFunc(arg0, arg1)
	}
	panic("ResolvesMultiArgs called with nil ResolvesMultiArgsFunc!")
}
