// Code generated by simplemock. DO NOT EDIT.
package named_return_test

type NamedReturnMock struct {
	NamedReturnFunc func() (x int)
}

func (m *NamedReturnMock) NamedReturn() (x int) {
	if m.NamedReturnFunc != nil {
		return m.NamedReturnFunc()
	}
	panic("NamedReturn called with nil NamedReturnFunc!")
}
